### ISSUE TITLE
Could not find org.tikv:tikv-client-java:4.0.0-SNAPSHOT.

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [TiFlink/TiFlink#3]
https://github.com/tikv/client-java.       the latest tag is v3.0.1

**Comment by shanzi** [comment]
暂时需要等待上游 client-java release 相关的代码。目前已经merge到master但是还没进release分支。

**Comment by shanzi** [comment]
Will be fixed by 3.2.0 of https://github.com/tikv/client-java
